### ISSUE TITLE
Question about usage of /metrics

### ISSUE THREAD

**Issue by jfallot** [cimnine/shelly-openmetrics-exporter#24]
I am trying to use the exporter to collect stats from a Shelly Plus PM Mini (Gen 2 power meter).
Calling the /probe?target=[shelly ip]:[shelly port] works fine but doing the same with the metrics endpoint  (/metrics?target=[shelly ip]:[shelly port]) is always returning only Go stats, nothing related to the Shelly device. I get the same Go stats if I specify a non existing target or without providing the target parameter:
what is the usage of the /metrics endpoint?

**Comment by cimnine** [comment]
The purpose is to monitor the exporter itself.
